name: mwmd per pandoc umwandeln

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - run: ls -la
      - run: tlmgr update --self && tlmgr install titling
      - uses: docker://pandoc/latex
        with:
          args: >-
            --standalone
            --pdf-engine=xelatex
            --template="layout/mwmd.tex"
            "layout/mwmd.yaml"
            "mwmd.md"
            --output="temp.pdf"
