name: mwmd per pandoc umwandeln

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout ...
        uses: actions/checkout@v2

      - name: Ablage
        run: mkdir Ablage

      - name: Timestamp ...
        run: echo "MWDW_TIMESTAMP=`date +'%Y-%m-%d--%H-%M-%S'`" >> $GITHUB_ENV

      - name: Test Timestamp ...
        run: echo ${{ env.MWDW_TIMESTAMP }}

      - name: Pandoc/LaTeX-Image ...
        uses: docker://pandoc/latex
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
             tlmgr update --self &&
             tlmgr install titling hanging &&
             pandoc --standalone --pdf-engine=xelatex --template=layout/mwmd.tex layout/mwmd.yaml mwmd.md --output=Ablage/temp.pdf
            "

      - name: Artifacts ...
        uses: actions/upload-artifact@master
        with:
          name: Ablage
          path: Ablage
