name: mwmd per pandoc umwandeln

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Pandoc/LaTeX-Image
        uses: docker://pandoc/latex:2.9
        command: apk add --no-cache texlive-latex-extra
        # with:
        #   args: >-
        #     --standalone
        #     --pdf-engine=xelatex
        #     --template="layout/mwmd.tex"
        #     "layout/mwmd.yaml"
        #     "mwmd.md"
        #     --output="temp.pdf"
