name: mwmd per pandoc umwandeln

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Pandoc/LaTeX-Image
        uses: docker://pandoc/latex
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
             tlmgr update --self &&
             tlmgr install  &&
             pandoc --standalone --pdf-engine=xelatex --template=layout/mwmd.tex layout/mwmd.yaml mwmd.md --output="temp.pdf"
            "
